### ISSUE TITLE
Project Stage 3 checklist (grading)

### ISSUE THREAD

**Issue by ad-jusk** [ad-jusk/TPUM_2024#12]
- [ ] program jest w .NET
- [ ] program się kompiluje
- [ ] testy jednostkowe na zielono
- [ ] można utworzyć jednocześnie dwie instancje programu (dwa procesy)
- [ ] instancje serwera i klienta współdziałają (test integracyjny)
- [ ] Oba programy maja wymagane warstwy Prezentacja, Logika, Dane
- [ ] Programy komunikują się z wykorzystaniem WebSocket
- [ ] Wykorzystano współdziałanie interaktywne
- [ ] Wykorzystano współdziałanie reaktywne (samorzutne/subskrypcja) z wykorzystaniem mechanizmu subskrypcji zrealizowanej poprzez implementację IObservable
- [ ] Wykorzystano serializacji z wykorzystaniem jednej ze składni `JSON`, `YAML`, `XML`
- [ ] wydzielono sekcję krytyczną i zabezpieczono w niej spójność danych
- [ ] Oba programy korzystają ze wspólnego modelu obiektowego
- [ ] Harmonizacja modeli - wygenerowano ekwiwalentny model i porównano go z napisanym ręcznie
